version: '3.4'

services:
  lil.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9000:80

  lil.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9100:80


  lil.sales:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9200:80


  lil.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 9300:80
    environment:
      - Services__Customers=http://lil.customers
      - Services__Products=http://lil.products
      - Services__Sales=http://lil.sales
